# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
s="The diameter of the {p:} is {q:} kilometers"
print(s.format(p=planet,q=diameter))


The diameter of the Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [9]:
array1=np.zeros(10)
print(array1)

NameError: ignored

In [10]:
array2=np.ones(10)*5
print(array2)

NameError: ignored

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
array3=np.arange(20,35,2)
print(array3)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
array4=np.arange(0,9).reshape(3,3)
print(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
s13=pd.DataFrame(index=np.arange(3),columns=np.arange(2))
print(s13)

     0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [15]:
s=pd.date_range(start='1-1-2023',end='2-10-2023')
print(s)

NameError: ignored

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [11]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [14]:
s=pd.DataFrame(lists)
print(s)

NameError: ignored